# Generated by Django 6.0 on 2025-12-28 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bmi', models.FloatField()),
                ('glucose', models.FloatField(help_text='Blood glucose level (mg/dL)')),
                ('systolic_bp', models.IntegerField(help_text='Systolic blood pressure')),
                ('diastolic_bp', models.IntegerField(help_text='Diastolic blood pressure')),
                ('hba1c', models.FloatField(help_text='HbA1c percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Metric',
                'verbose_name_plural': 'Health Metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifestyleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_pattern', models.CharField(blank=True, max_length=100)),
                ('exercise_minutes', models.IntegerField(help_text='Daily exercise in minutes')),
                ('sleep_hours', models.FloatField(help_text='Average sleep hours per night')),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('smoking_status', models.CharField(choices=[('never', 'Never'), ('former', 'Former'), ('current', 'Current')], default='never', max_length=20)),
                ('family_history', models.BooleanField(default=False, help_text='Family history of diabetes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lifestyle Data',
                'verbose_name_plural': 'Lifestyle Data',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score', models.FloatField(help_text='Risk score (0-100)')),
                ('risk_stage', models.CharField(choices=[('normal', 'Normal'), ('pre-diabetic', 'Pre-diabetic'), ('high-risk', 'High Risk')], max_length=20)),
                ('trend', models.JSONField(blank=True, help_text='6-12 month risk trend data', null=True)),
                ('explanation', models.JSONField(blank=True, help_text='Explainable AI feature importance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('health_metrics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.healthmetrics')),
                ('lifestyle_data', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.lifestyledata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prediction Result',
                'verbose_name_plural': 'Prediction Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LifestyleRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_text', models.TextField()),
                ('impact_percentage', models.FloatField(help_text='Expected risk reduction %')),
                ('priority', models.IntegerField(help_text='Priority order (1=highest)')),
                ('category', models.CharField(help_text='e.g., Exercise, Diet, Sleep', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='api.predictionresults')),
            ],
            options={
                'verbose_name': 'Lifestyle Recommendation',
                'verbose_name_plural': 'Lifestyle Recommendations',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ComplicationRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kidney_risk', models.FloatField(help_text='Kidney complication risk (0-100)')),
                ('eye_risk', models.FloatField(help_text='Eye damage risk (0-100)')),
                ('nerve_risk', models.FloatField(help_text='Neuropathy risk (0-100)')),
                ('cardiovascular_risk', models.FloatField(default=0, help_text='Heart disease risk (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complication_risks', to=settings.AUTH_USER_MODEL)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complications', to='api.predictionresults')),
            ],
            options={
                'verbose_name': 'Complication Risk',
                'verbose_name_plural': 'Complication Risks',
                'ordering': ['-created_at'],
            },
        ),
    ]
